FROM nvcr.io/nvidia/pytorch:22.04-py3

WORKDIR /app

RUN mkdir /models

COPY requirements.txt .

RUN python3 -m pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . .

CMD ["ls"]

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]